import { Interval } from "./interval";
import { NoteName } from "./note-name";
import { NoteValue } from "./note-value";
import { Pitch } from "./pitch";
import { Chord } from "./playable/chord";
import { Phrase } from "./playable/phrase";

export {
  Phrase,
  Chord,
  Interval,
}


export const C = new Pitch(NoteName.C, "Inferred");
export const Cs = new Pitch(NoteName.Cs, "Inferred");
export const Db = new Pitch(NoteName.Db, "Inferred");
export const D = new Pitch(NoteName.D, "Inferred");
export const Ds = new Pitch(NoteName.Ds, "Inferred");
export const Eb = new Pitch(NoteName.Eb, "Inferred");
export const E = new Pitch(NoteName.E, "Inferred");
export const Fb = new Pitch(NoteName.Fb, "Inferred");
export const F = new Pitch(NoteName.F, "Inferred");
export const Fs = new Pitch(NoteName.Fs, "Inferred");
export const Gb = new Pitch(NoteName.Gb, "Inferred");
export const G = new Pitch(NoteName.G, "Inferred");
export const Gs = new Pitch(NoteName.Gs, "Inferred");
export const Ab = new Pitch(NoteName.Ab, "Inferred");
export const A = new Pitch(NoteName.A, "Inferred");
export const As = new Pitch(NoteName.As, "Inferred");
export const Bb = new Pitch(NoteName.Bb, "Inferred");
export const B = new Pitch(NoteName.B, "Inferred");
export const Cb = new Pitch(NoteName.Cb, "Inferred");

export const C1 = new Pitch(NoteName.C, 1);
export const C2 = new Pitch(NoteName.C, 2);
export const C3 = new Pitch(NoteName.C, 3);
export const C4 = new Pitch(NoteName.C, 4);
export const C5 = new Pitch(NoteName.C, 5);
export const C6 = new Pitch(NoteName.C, 6);
export const C7 = new Pitch(NoteName.C, 7);
export const Db1 = new Pitch(NoteName.Db, 1);
export const Db2 = new Pitch(NoteName.Db, 2);
export const Db3 = new Pitch(NoteName.Db, 3);
export const Db4 = new Pitch(NoteName.Db, 4);
export const Db5 = new Pitch(NoteName.Db, 5);
export const Db6 = new Pitch(NoteName.Db, 6);
export const Db7 = new Pitch(NoteName.Db, 7);
export const D1 = new Pitch(NoteName.D, 1);
export const D2 = new Pitch(NoteName.D, 2);
export const D3 = new Pitch(NoteName.D, 3);
export const D4 = new Pitch(NoteName.D, 4);
export const D5 = new Pitch(NoteName.D, 5);
export const D6 = new Pitch(NoteName.D, 6);
export const D7 = new Pitch(NoteName.D, 7);
export const Eb1 = new Pitch(NoteName.Eb, 1);
export const Eb2 = new Pitch(NoteName.Eb, 2);
export const Eb3 = new Pitch(NoteName.Eb, 3);
export const Eb4 = new Pitch(NoteName.Eb, 4);
export const Eb5 = new Pitch(NoteName.Eb, 5);
export const Eb6 = new Pitch(NoteName.Eb, 6);
export const Eb7 = new Pitch(NoteName.Eb, 7);
export const E1 = new Pitch(NoteName.E, 1);
export const E2 = new Pitch(NoteName.E, 2);
export const E3 = new Pitch(NoteName.E, 3);
export const E4 = new Pitch(NoteName.E, 4);
export const E5 = new Pitch(NoteName.E, 5);
export const E6 = new Pitch(NoteName.E, 6);
export const E7 = new Pitch(NoteName.E, 7);
export const F1 = new Pitch(NoteName.F, 1);
export const F2 = new Pitch(NoteName.F, 2);
export const F3 = new Pitch(NoteName.F, 3);
export const F4 = new Pitch(NoteName.F, 4);
export const F5 = new Pitch(NoteName.F, 5);
export const F6 = new Pitch(NoteName.F, 6);
export const F7 = new Pitch(NoteName.F, 7);
export const Fb1 = new Pitch(NoteName.Fb, 1);
export const Fb2 = new Pitch(NoteName.Fb, 2);
export const Fb3 = new Pitch(NoteName.Fb, 3);
export const Fb4 = new Pitch(NoteName.Fb, 4);
export const Fb5 = new Pitch(NoteName.Fb, 5);
export const Fb6 = new Pitch(NoteName.Fb, 6);
export const Fb7 = new Pitch(NoteName.Fb, 7);
export const Gb1 = new Pitch(NoteName.Gb, 1);
export const Gb2 = new Pitch(NoteName.Gb, 2);
export const Gb3 = new Pitch(NoteName.Gb, 3);
export const Gb4 = new Pitch(NoteName.Gb, 4);
export const Gb5 = new Pitch(NoteName.Gb, 5);
export const Gb6 = new Pitch(NoteName.Gb, 6);
export const Gb7 = new Pitch(NoteName.Gb, 7);
export const G1 = new Pitch(NoteName.G, 1);
export const G2 = new Pitch(NoteName.G, 2);
export const G3 = new Pitch(NoteName.G, 3);
export const G4 = new Pitch(NoteName.G, 4);
export const G5 = new Pitch(NoteName.G, 5);
export const G6 = new Pitch(NoteName.G, 6);
export const G7 = new Pitch(NoteName.G, 7);
export const Ab1 = new Pitch(NoteName.Ab, 1);
export const Ab2 = new Pitch(NoteName.Ab, 2);
export const Ab3 = new Pitch(NoteName.Ab, 3);
export const Ab4 = new Pitch(NoteName.Ab, 4);
export const Ab5 = new Pitch(NoteName.Ab, 5);
export const Ab6 = new Pitch(NoteName.Ab, 6);
export const Ab7 = new Pitch(NoteName.Ab, 7);
export const A1 = new Pitch(NoteName.A, 1);
export const A2 = new Pitch(NoteName.A, 2);
export const A3 = new Pitch(NoteName.A, 3);
export const A4 = new Pitch(NoteName.A, 4);
export const A5 = new Pitch(NoteName.A, 5);
export const A6 = new Pitch(NoteName.A, 6);
export const A7 = new Pitch(NoteName.A, 7);
export const Bb1 = new Pitch(NoteName.Bb, 1);
export const Bb2 = new Pitch(NoteName.Bb, 2);
export const Bb3 = new Pitch(NoteName.Bb, 3);
export const Bb4 = new Pitch(NoteName.Bb, 4);
export const Bb5 = new Pitch(NoteName.Bb, 5);
export const Bb6 = new Pitch(NoteName.Bb, 6);
export const Bb7 = new Pitch(NoteName.Bb, 7);
export const B1 = new Pitch(NoteName.B, 1);
export const B2 = new Pitch(NoteName.B, 2);
export const B3 = new Pitch(NoteName.B, 3);
export const B4 = new Pitch(NoteName.B, 4);
export const B5 = new Pitch(NoteName.B, 5);
export const B6 = new Pitch(NoteName.B, 6);
export const B7 = new Pitch(NoteName.B, 7);
export const Cb1 = new Pitch(NoteName.Cb, 1);
export const Cb2 = new Pitch(NoteName.Cb, 2);
export const Cb3 = new Pitch(NoteName.Cb, 3);
export const Cb4 = new Pitch(NoteName.Cb, 4);
export const Cb5 = new Pitch(NoteName.Cb, 5);
export const Cb6 = new Pitch(NoteName.Cb, 6);
export const Cb7 = new Pitch(NoteName.Cb, 7);

export const w = NoteValue.Whole;
export const h = NoteValue.Half;
export const d2 = NoteValue.DottedHalf;
export const dh = NoteValue.DottedHalf;
export const q = NoteValue.Quarter;
export const dq = NoteValue.DottedQuarter;
export const d4 = NoteValue.DottedQuarter;
export const e = NoteValue.Eighth;
export const de = NoteValue.DottedEighth;
export const d8 = NoteValue.DottedEighth;
export const s = NoteValue.Sixteenth;
export const ds = NoteValue.DottedSixteenth;
export const d16 = NoteValue.DottedSixteenth;
export const t = NoteValue.ThirtySecond;
export const dt = NoteValue.DottedThirtySecond;
export const d32 = NoteValue.DottedThirtySecond;
export const h3 = NoteValue.HalfTriplet;
export const q3 = NoteValue.QuarterTriplet;
export const e3 = NoteValue.EighthTriplet;
export const s3 = NoteValue.SixteenthTriplet;
export const t3 = NoteValue.ThirtySecondTriplet;
export const r = "REST";

export const I = Interval.Unison;
export const II = Interval.Maj2;
export const IIb = Interval.min2;
export const III = Interval.Maj3;
export const IIIb = Interval.min3;
export const IV = Interval.Fourth;
export const V = Interval.Fifth;
export const Vb = Interval.Tritone;
export const VI = Interval.Maj6;
export const VIb = Interval.min6;
export const VIIb = Interval.min7;
export const VII = Interval.Maj7;
export const VIII = Interval.Octave;
